## ------------------------------------------------------------
## Quickstart Configuration
## This document contains configuration for the quickstart
##
## ------------------------------------------------------------

appTypes:
  - title: Native App
    name: native
    descriptioiOS SDK"
    question: "Select a native SDK"
    budicon: 243
    slug: native-platforms

  - title: Single-Page Web App
    name: spa
    description: " JavaScript front-end app that uses an API."
    example: "eg: AngularJS, React"
    question: "What technology are you using for your web app?"
    budicon: 349
    slug: application-platforms

  - title: Regular Web App
    name: webapp
    description: "Traditional server-side rendered web app."
    example: "eg: Express.js, ASP.NET"
    question: "What technology are you using for your web app?"
    budicon: 349
    slug: server-platforms
    
  - title: Machine to Machine App
    name: backend
    description: "A CLI, Daemon, or Service running on your backend."
    example: "eg: Hapi.js API, ASP.NET API"
    question: "Select an API or backend platform"
    budicon: 649
    slug: server-apis
