## ------------------------------------------------------------
## Sidebar Nav Configuration
## This document contains configuration for the sidebar
##
## ------------------------------------------------------------

articles:

  - title: Getting Started
    url: "/overview"
    children:
      - title: Overview
        url: /overview

      - title: Developer Videos
        url: /videos

      - title: Architecture Scenarios
        url: /architecture-scenarios

  - title: "Clients"
    url: "/clients"

  - title: "APIs"
    url: "/apis"
    children:
      - title: "API Authorization"
        url: "/api-auth"

  - title: "Connections"
    url: "/connections"
    children:
      - title: "Username/Password Connection"
        url: "/connections/database"

      - title: "Social Connections"
        url: "/identityproviders#social"
        children:
          - title: "Custom Social Extensions"
            url: "/extensions/custom-social-extensions"

      - title: "Custom Database Connections"
        url: "/connections/database/mysql"

      - title: "Enterprise Identity Providers"
        url: "/identityproviders#enterprise"

      - title: "Passwordless Authentication"
        url: "/connections/passwordless"
        children:
          - title: "Overview"
            url: "/connections/passwordless"

          - title: "Email Passwordless Authentication"
            url: "/connections/passwordless/email"

          - title: "SMS Passwordless Authentication"
            url: "/connections/passwordless/sms"

          - title: "FAQ"
            url: "/connections/passwordless/faq"

  - title: "Rules"
    url: "/rules"
    children:

      - title: "Overview"
        url: "/rules"

      - title: "User Metadata in Rules"
        url: "/rules/metadata-in-rules"

      - title: "Deploy Rules with GitHub"
        url: "/extensions/github-deploy"

      - title: "Deploy Rules with Bitbucket"
        url: "/extensions/bitbucket-deploy"

      - title: "Deploy Rules with GitLab"
        url: "/extensions/gitlab-deploy"

  - title: "Hooks (Beta)"
    url: "/hooks"
    children:

      - title: "Overview"
        url: "/hooks"

      - title: "Extensibility Points"
        url: "/hooks/extensibility-points"

      - title: "Using the Auth0 CLI"
        url: "/hooks/cli"

      - title: "Using the Management Dashboard"
        url: "/hooks/dashboard"

  - title: "Email"
    url: "/email"
    children:
      - title: "Overview"
        url: "/email"

      - title: "Custom Email Handling"
        url: "/email/custom"

      - title: "Customizing Your Emails"
        url: "/email/templates"

  - title: "Password Policies"
    url: "/connections/database/password-options"
    children:
      - title: "Password Options"
        url: "/connections/database/password-options"

      - title: "Password Strength"
        url: "/connections/database/password-strength"

  - title: "User Management"
    url: "/user-profile"
    children:
      - title: "User Profiles"
        url: "/user-profile"

      - title: "User Metadata"
        url: "/metadata"

      - title: "User Impersonation"
        url: "/user-profile/user-impersonation"

      - title: "Delegated Administration"
        url: "/extensions/delegated-admin"

      - title: "Authorization"
        url: "/extensions/authorization-extension"
        children:
          - title: "Groups"
            url: "/extensions/authorization-extension#groups"

          - title: "Roles"
            url: "/extensions/authorization-extension#roles"

          - title: "Permissions"
            url: "/extensions/authorization-extension#permissions"

  - title: "Multifactor Authentication"
    url: "/multifactor-authentication"
    children:
      - title: "Overview"
        url: "/multifactor-authentication"

      - title: "Guardian"
        url: "/multifactor-authentication/guardian"
        children:
          - title: "For Administrators"
            url: "/multifactor-authentication/administrator"

          - title: "For Developers"
            url: "/multifactor-authentication/developer"

          - title: "For Users"
            url: "/multifactor-authentication/user-guide"

      - title: "SMS"
        url: "/multifactor-authentication#mfa-with-sms"

      - title: "Google Authenticator"
        url: "/multifactor-authentication/google-authenticator"

      - title: "Duo Security"
        url: "/multifactor-authentication/duo"


  - title: "Anomaly Detection"
    url: "/anomaly-detection"

  - title: "Addons/Third-Party Applications"
    url: "/addons"
