## ------------------------------------------------------------
## Sidebar Nav Configuration
## This document contains configuration for the sidebar
##
## ------------------------------------------------------------

articles:

  - title: Getting Started
    url: "/overview"
    children:
      - title: Overview
        url: /overview

      - title: "Clients"
        url: "/clients"

      - title: "APIs"
        url: "/apis"

      - title: Developer Videos
        url: /videos

      - title: Architecture Scenarios
        url: /architecture-scenarios

  - title: "Username/Password Connection"
    url: "/connections/database"

  - title: "Rules"
    url: "/rules"
    children:

      - title: "Overview"
        url: "/rules"

      - title: "User Metadata in Rules"
        url: "/rules/metadata-in-rules"

      - title: "Deploy Rules with GitHub"
        url: "/extensions/github-deploy"

      - title: "Deploy Rules with Bitbucket"
        url: "/extensions/bitbucket-deploy"

      - title: "Deploy Rules with GitLab"
        url: "/extensions/gitlab-deploy"

  - title: "Hooks"
    url: "/hooks"
    children:

      - title: "Overview"
        url: "/hooks"

      - title: "Extensibility Points"
        url: "/hooks/extensibility-points"

      - title: "Using the Auth0 CLI"
        url: "/hooks/cli"

      - title: "Using the Management Dashboard"
        url: "/hooks/dashboard"

  - title: "Email"
    children:
      - title: "Overview"
        url: "/email"

      - title: "Custom Email Handling"
        url: "/email/custom"

      - title: "Customizing Your Emails"
        url: "/email/templates"

  - title: "Social Users"
    url: "/extensions/custom-social-extensions"

  - title: "Password Policies"
    url: "/connections/database/password-options"
    children:
      - title: "Password Options"
        url: "/connections/database/password-options"

      - title: "Password Strength"
        url: "/connections/database/password-strength"

  - title: "User Metadata"
    url: "/metadata"

  - title: "User Impersonation"
    url: "/user-profile/user-impersonation"

  - title: "Multifactor Authentication"
    children:
      - title: "Overview"
        url: "/multifactor-authentication"

      - title: "Guardian"
        url: "/multifactor-authentication/guardian"
        children:
          - title: "For Administrators"
            url: "/multifactor-authentication/administrator"

          - title: "For Developers"
            url: "/multifactor-authentication/developer"

          - title: "For Users"
            url: "/multifactor-authentication/user-guide"

      - title: "SMS"
        url: "/multifactor-authentication#mfa-with-sms"

      - title: "Google Authenticator"
        url: "/multifactor-authentication/google-authenticator"

      - title: "Duo Security"
        url: "/multifactor-authentication/duo"

  - title: "Custom Database Connections"
    url: "/connections/database/mysql"

  - title: "Enterprise Identity Providers"
    url: "/identityproviders#enterprise"

  - title: "Anomaly Detection"
    url: "/anomaly-detection"

  - title: "Addons/Third-Party Applications"
    url: "/addons"

  - title: "Passwordless Authentication"
    url: "/connections/passwordless"
    children:
      - title: "Overview"
        url: "/connections/passwordless"

      - title: "Email Passwordless Authentication"
        url: "/passwordless/email"

      - title: "SMS Passwordless Authentication"
        url: "/passwordless/sms"

      - title: "FAQ"
        url: "/passwordless/faq"
