## ------------------------------------------------------------
## Sidebar Nav Configuration
## This document contains configuration for the sidebar
##
## ------------------------------------------------------------

articles:

  - title: Getting Started
    url: "/overview"
    children:
      - title: Overview
        url: /overview
      - title: Developer Videos
        url: /videos
      - title: Architecture Scenarios
        url: /architecture-scenarios

  - title: "Lock"
    url: "/libraries/lock"
    children:
      - title: "Lock for Web"
        url: "/libraries/lock"

      - title: "Lock for iOS"
        url: "/libraries/lock-ios"

      - title: "Lock for Android"
        url: "/libraries/lock-android"

      - title: "Lock vs. Custom UI"
        url: "/libraries/when-to-use-lock"

  - title: "Applications"
    url: "/applications"
    icon: "icon-budicon-349"

  - title: "Rules"
    url: "/rules"
    children:

      - title: "Deploy Rules with Github"
        url: "/extensions/github-deploy"

      - title: "Deploy Rules with Bitbucket"
        url: "/extensions/bitbucket-deploy"

  - title: "Extensions"
    url: "/extensions"
    children:

      - title: "Creating Extensions"
        url: "/extensions/custom-extensions"

      - title: "User Import / Export Extension"
        url: "/extensions/user-import-export"

      - title: "Authorization Extension"
        url: "/extensions/authorization-extension"

  - title: "Identity Providers"
    url: "/identityproviders"
    children:

      - title: "Custom Social Connections"
        url: "/extensions/custom-social-extensions"

  - title: "Single Sign-On"
    url: "/sso"

  - title: "User Profile"
    url: "/user-profile"
    children:

      - title: "Metadata"
        url: "/metadata"
        children:

          - title: "Updating with Lock"
            url: "/metadata/lock"

          - title: "Updating with API"
            url: "/metadata/management-api"

          - title: "Data Storage Guidance"
            url: "/user-profile/user-data-storage"

      - title: "Normalized User Profile"
        url: "/user-profile/normalized"

      - title: "Progressive Profiling"
        url: "/user-profile/progressive-profiling"

  - title: "Multifactor Authentication"
    url: "/multifactor-authentication"
    children:

      - title: "Auth0 Guardian"
        url: "/multifactor-authentication/guardian"
        children:

          - title: "Admin Guide"
            url: "/multifactor-authentication/guardian/admin-guide"

          - title: "Dev Guide"
            url: "/multifactor-authentication/guardian/dev-guide"

          - title: "User Guide"
            url: "/multifactor-authentication/guardian/user-guide"

      - title: "SMS"
        url: "/multifactor-authentication#mfa-with-sms"

      - title: "Google Authenticator"
        url: "/multifactor-authentication/google-authenticator"

      - title: "Duo Security"
        url: "/multifactor-authentication/duo"

      # - title: "Custom MFA"
      #   url: "/multifactor-authentication#mfa-using-a-custom-provider"

        # children:
        #
        #   - title: "Admin Guide"
        #     url: "/multifactor-authentication/google-auth/admin-guide"
        #
        #   - title: "Dev Guide"
        #     url: "/multifactor-authentication/google-auth/dev-guide"
        #
        #   - title: "User Guide"
        #     url: "/multifactor-authentication/google-auth/user-guide"

  - title: "Passwordless Authentication"
    url: "/connections/passwordless"

  - title: "AD Connector"
    url: "/connector"
    children:

      - title: "Health Monitoring Extension"
        url: "/extensions/adldap-connector"

  - title: "CMS Plugins"
    url: "/cms"
    children:

      # - title: "Wordpress"
      #   url: "/cms#wordpress-plugin"
      #
      # - title: "Joomla"
      #   url: "/cms#joomla-extension"

      - title: "SharePoint"
        url: "https://github.com/auth0/auth0-sharepoint"


apis:

  - title: "Overview"
    url: "/api/info"

  - title: "Testing with Postman"
    url: "/api/postman"

  - title: Authentication API
    url: "/api/authentication"
    forceFullReload: true

  - title: Management API
    url: "/api/management/v2/"
    forceFullReload: true
    children:
      - title: API Tokens
        url: /api/management/v2/tokens
        forceFullReload: true
      - title: Query String Syntax
        url: /api/management/v2/query-string-syntax
        forceFullReload: true
      - title: User Search
        url: /api/management/v2/user-search
        forceFullReload: true




appliance:

  - title: "Introduction"
    url: "/appliance"

  - title: "Appliance Planning"
    url: "/appliance/appliance-overview"
    children:
      - title: Geographic High-Availability
        url: /appliance/geo-ha
      - title: Infrastructure Requirements
        url: /appliance/infrastructure
      - title: Customer Onboarding
        url: /onboarding/appliance-sprint
      - title: Onboarding Requirements
        url: /appliance/private-cloud-requirements

  - title: "Appliance Administration"
    url: "/appliance/admin"
    children:
      - title: Release Notes
        url: https://auth0.com/changelog/appliance
      - title: Administrator's Manual
        url: /appliance/admin
      - title: Dashboard/Configuration Area
        url: /appliance/dashboard
      - title: Monitoring Tools
        url: /appliance/monitoring
      - title: Command-Line Interface Tools
        url: /appliance/cli
      - title: Automatic Tenant Creation
        url: /appliance/admin/creating-tenants
      - title: Node Module Availibility
        url: /appliance/modules
      - title: Webtasks
        url: /appliance/webtasks
      - title: Disaster Recovery
        url: /appliance/geo-ha/disaster-recovery
