lock_url: 'https://cdn.auth0.com/js/lock/10.6/lock.min.js'
lock_passwordless_url: 'https://cdn.auth0.com/js/lock-passwordless-2.2.min.js'
auth0js_url: 'https://cdn.auth0.com/w2/auth0-7.6.min.js'
auth0js_8_url: 'http://cdn.auth0.com/js/auth0/8.0/auth0.min.js'