lock_url: 'https://cdn.auth0.com/js/lock/10.6/lock.min.js'
lock_passwordless_url: 'https://cdn.auth0.com/js/lock-passwordless-2.2.min.js'
auth0js_url: 'https://cdn.auth0.com/w2/auth0-7.4.min.js'
auth0android_url: 'https://github.com/auth0/Auth0.Android'
